name: Clippy

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: "Install Rust toolchain"
        run: rustup component add clippy
      - name: Run clippy
        run: make lint
