name: Spelling

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

jobs:
  typos:
      name: "Spell check"
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: crate-ci/typos@master
          with:
            files: .
