# For this action to work you must explicitly allow GitHub Actions to create pull requests.
# This setting can be found in a repository's settings under Actions > General > Workflow permissions.
# For repositories belonging to an organization, this setting can be managed by
# admins in organization settings under Actions > General > Workflow permissions.
name: Sync Python Releases
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    if: github.repository == 'mitsuhiko/rye'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rye
        uses: eifinger/setup-rye@v1
        with:
          enable-cache: true
      - name: Sync Python Releases
        run: make sync-python-releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Sync latest Python releases"
          add-paths: "rye/src/downloads.inc"
          branch: "sync-python-releases"
          title: "Sync Python Releases"
          body: |
            - Synced latest Python releases

            <sup>Auto-generated by [sync-python-releases.yml](https://github.com/mitsuhiko/rye/blob/main/.github/workflows/sync-python-releases.yml)</sup>
